name: elephant_client
description: Elephant

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  postgres: ^2.4.1+2
  shared_preferences: ^2.0.8
  file_picker: ^4.1.3
  image_compression: ^1.0.3
  http: ^0.13.4
  drag_and_drop_gridview: ^1.0.8

dev_dependencies:

  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "./Ressources/Logo.ico"
  android: true
  ios: true
  windows: true
  linux: true

flutter:
  uses-material-design: true